// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleSongs.DAL;

namespace SimpleSongs.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20211004113822_SeededDatabaseSuccessfully")]
    partial class SeededDatabaseSuccessfully
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("SimpleSongs.Models.Song", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlbumName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<double>("Length")
                        .HasColumnType("REAL");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AlbumName = "In Dreams",
                            Author = "Roy Orbison",
                            Length = 2.1499999999999999,
                            Title = "House Without Windows"
                        },
                        new
                        {
                            ID = 2,
                            AlbumName = "In Dreams",
                            Author = "Roy Orbison",
                            Length = 2.5099999999999998,
                            Title = "In Dreams"
                        },
                        new
                        {
                            ID = 3,
                            AlbumName = "In Dreams",
                            Author = "Roy Orbison",
                            Length = 2.5699999999999998,
                            Title = "Lonely Wine"
                        },
                        new
                        {
                            ID = 4,
                            AlbumName = "S&M",
                            Author = "Metallica",
                            Length = 4.3600000000000003,
                            Title = "Fuel"
                        },
                        new
                        {
                            ID = 5,
                            AlbumName = "S&M",
                            Author = "Metallica",
                            Length = 9.3399999999999999,
                            Title = "Master of Puppets"
                        },
                        new
                        {
                            ID = 6,
                            AlbumName = "Load",
                            Author = "Metallica",
                            Length = 5.2000000000000002,
                            Title = "Mama Said"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
